import type { Request, Response } from "express";

interface ChartData {
  type: string;
  title: string;
  data: Record<string, unknown>[];
  keys: string[];
}

interface ReportRequest {
  sql: string;
  charts: ChartData[];
  table: Record<string, unknown>[];
  datasetName: string;
}

function generateMarkdownReport(req: ReportRequest): string {
  const { sql, charts, table, datasetName } = req;
  const now = new Date().toLocaleString();

  let markdown = `# Business Report

Generated: ${now}
Dataset: ${datasetName}

## Executive Summary

This report presents key insights and findings from the data analysis of ${datasetName}.

## SQL Query

\`\`\`sql
${sql}
\`\`\`

## Dashboard Charts

`;

  // Add chart information
  charts.forEach((chart, idx) => {
    markdown += `### Chart ${idx + 1}: ${chart.title}\n`;
    markdown += `**Type**: ${chart.type}\n`;
    markdown += `**Data Points**: ${chart.data.length}\n\n`;

    // Add data summary
    if (chart.data.length > 0) {
      markdown += `#### Data Summary\n\n`;
      markdown += "| ";
      const headers = ["name", ...chart.keys];
      markdown += headers.join(" | ") + " |\n";
      markdown += "| " + headers.map(() => "---").join(" | ") + " |\n";

      chart.data.slice(0, 10).forEach((row: Record<string, unknown>) => {
        markdown += "| ";
        markdown += (row.name || "-");
        chart.keys.forEach((key) => {
          const val = row[key];
          markdown += " | " + (typeof val === "number" ? val.toFixed(2) : val || "-");
        });
        markdown += " |\n";
      });

      if (chart.data.length > 10) {
        markdown += `\n*Table shows first 10 of ${chart.data.length} records*\n`;
      }
    }

    markdown += "\n";
  });

  // Add data highlights
  if (table.length > 0) {
    markdown += `## Data Highlights\n\n`;
    markdown += `Total Records: ${table.length}\n\n`;

    // Calculate some basic statistics
    const firstRow = table[0];
    if (firstRow) {
      markdown += `### Available Columns\n\n`;
      Object.keys(firstRow).forEach((key) => {
        markdown += `- ${key}\n`;
      });
    }
  }

  markdown += `
## Business Recommendations

Based on the analysis of ${datasetName}:

1. Review the charts and tables above for key patterns and trends
2. Consider follow-up analysis to drill deeper into areas of interest
3. Use these insights to inform business decisions and strategy

---

*This report was auto-generated by InsightAI V3*
`;

  return markdown;
}

export default async function generateReportHandler(req: Request, res: Response) {
  try {
    const reportData = req.body as ReportRequest;

    if (!reportData.sql || !Array.isArray(reportData.charts)) {
      return res.status(400).json({
        error: "Missing required fields: sql and charts",
      });
    }

    const markdown = generateMarkdownReport(reportData);

    return res.json({
      markdown,
      timestamp: new Date().toISOString(),
    });
  } catch (error) {
    console.error("Report generation error:", error);
    return res.status(500).json({
      error: error instanceof Error ? error.message : "Report generation failed",
    });
  }
}
